package by.tc.web.controller.control.command.activity;

public enum ControllerActivity {
    // Common activities
    AUTHENTICATE,
    LOCALIZE,
    CLOSE_SESSION,

    UPDATE_ACCOUNT,
    DELETE_ACCOUNT,

    DISPLAY_ORDERS,

    // Customer activities
    REGISTER_CUSTOMER,
    DISPLAY_ORDER_TAXI_PAGE,
    ORDER_TAXI,
    CANCEL_ORDER,
    RATE_ORDER,
    FIND_TAXIDRIVER,
    GET_ACTIVE_CUSTOMER_ORDER,


    // Driver activities
    GET_ACTIVE_TAXIDRIVER_ORDER,
    CHECK_ORDERS,
    CHOOSE_ORDER,
    ACCEPT_ORDER,
    FINISH_ORDER,


    // Administrator activities
    DISPLAY_CUSTOMERS,
    DISPLAY_CUSTOMER,
    BLOCK_CUSTOMER,
    UNBLOCK_CUSTOMER,
    DISCOUNT_CUSTOMER,

    DISPLAY_TAXIDRIVERS,
    DISPLAY_TAXIDRIVER,
    REGISTER_TAXIDRIVER,
    BLOCK_TAXIDRIVER,
    UNBLOCK_TAXIDRIVER,

    DISPLAY_ORDER,
    DELETE_ORDER
}
