package by.tc.web.controller.control.command.activity;

public enum ControllerActivity {
    AUTHENTICATE, REGISTER_CUSTOMER, LOCALIZE, CLOSE_SESSION,


    // Administrator activities
    DISPLAY_CUSTOMERS,
    DISPLAY_CUSTOMER,
    BLOCK_CUSTOMER,
    UNBLOCK_CUSTOMER,
    DISCOUNT_CUSTOMER,

    DISPLAY_TAXIDRIVERS,
    DISPLAY_TAXIDRIVER,
    REGISTER_TAXIDRIVER,
    BLOCK_TAXIDRIVER,
    UNBLOCK_TAXIDRIVER
}
